@startuml


ModelPublication "1" --|>  "1" ModelExtension
ModelPublication "1" --|>  "n" ModelIntension

Instance "1" --|>  "1" ModelPublication

Instance "1" --|>  "n" InstanceTag


ModelExtension "1" o--right--|> "n" ModelIntension

class ModelExtension {
    String id // ext_id
    String owner_id // extension's owner
    String group
    String name
    String tree
    Structure structure
    Visibility visibility
    DateTime begin_time
    DateTime end_time
}

class ModelIntension {
    String id // int_id
    String ext_id
    String field
    Boolean single
    Structure structure
    Visibility visibility
    DateTime begin_time
    DateTime end_time
}

class ModelPublication {
    String id // m_tag_id
    String owner_id
    String ext_id
    String[] int_id
    String version
    Publication publication
    Visibility visibility
    DateTime created_at
}

enum Structure {
    STRING
    NATURE
    BOOL
    REAL
    FLOAT
    COMPLEX
    DATETIME
}

enum Publication {
    SNAPSHOT
    RELEASE
}

enum Visibility {
    PRIVATE
    PROTECTED
    PUBLIC
}

class Instance {
    String id // i_id
    String owner_id // instance's owner
    String m_tag_id
    String field
    String value
    String value_set_hash
    String value_ref_id
    DateTime begin_time
    DateTime end_time
}

class InstanceTag {
    String id // i_tag_id
    String owner_id // instance's owner
    String[] i_id
    Publication publication
    DateTime created_at
    Visibility visibility
}

@enduml



