@startuml


'Instance "1" --|>  "n" InstanceTag

Instance "1" --left-|>  "1" ModelSubscription

Model "1" -up-|>  "n" ModelSubscription

Model "1" --|>  "n" ModelPublication

ModelPublication "1" --|>  "1" Extension
ModelPublication "1" --|>  "n" Intension

Extension "1" o--right--|> "n" Intension

Entity "1" -up-|> "n" Instance

AssetPublication "1" -up-|> "1" Entity

AssetSubscription "1" -down-|> "1" Asset

Asset "1" --|> "n" AssetPublication

class Asset {
    Subject provider_id
    Subject visitor_id
    DateTime begin_time
    DateTime end_time
}

class AssetSubscription{
    string id
    string pub_set_hash
    string instance_id
    Visibility visibility
    Publication publication
    Subject provider_id
    string version
    ---
    Subject operator_id
    DateTime begin_time
    DateTime end_time
}

class AssetPublication{
    string id
    string pub_set_hash
    string ins_id
    Visibility visibility
    Subject provider_id
    Publication publication
    string version
    ---
    Subject operator_id
    DateTime begin_time
    DateTime end_time
}

class Entity {
    Subject owner_id
    Instance[] instances
    Intension[] intensions
}

class Model {
    string pub_set_hash
    Subject provider_id
    string group
    string name
    string ext_id
    string version
    Publication publication
    Date begin_time
}

class Extension {
    string id // ext_id
    Subject owner_id // extension's owner
    string group
    string name
    string tree
    Visibility visibility
    ---
    Subject operator_id
    DateTime begin_time
    DateTime end_time
}

class Intension {
    string id // int_id
    string ext_id
    string field
    Boolean single
    Structure structure
    string ref_ext_id
    Visibility visibility
    ---
    Subject operator_id
    DateTime begin_time
    DateTime end_time
}

class ModelPublication {
    string id // pub_id
    string pub_set_hash
    Subject provider_id
    string ext_id
    string int_id
    ---
    Publication publication
    string version
    Visibility visibility
    ---
    Subject operator_id
    DateTime begin_time
    DateTime end_time
}

class ModelSubscription {
    string id // sub_id
    string pub_set_hash
    Subject subscriber_id
    string group
    string name
    string tree
    ---
    Subject operator_id
    DateTime begin_time
    DateTime end_time
}

class Instance {
    string id // ins_id
    Subject owner_id
    string sub_id
    string ext_id
    string int_id
    string field
    string value
    string value_set_hash
    string value_ref_id
    ---
    Subject operator_id
    DateTime begin_time
    DateTime end_time
}

enum Publication {
    SNAPSHOT
    RELEASE
}

enum Visibility {
    PRIVATE
    PROTECTED
    PUBLIC
}

enum Subject {
    OWNER
    PROVIDER
    SUBSCRIBER
    VISITOR     // read only
    OPERATOR    // read&write
}


@enduml



