spring:
  profiles: common
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 9090
---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://hp-mini.sinewang.com/kiimate?autoReconnect=true
    username: root
    password: wave
logging:
  level:
    com.sinewang: DEBUG
    one.kii: DEBUG
---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://10.10.10.44:33307/kiimate?autoReconnect=true