spring:
  profiles: common
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.10.10.44:33307/metamate?autoReconnect=true
    username: root
    password: 2fJicd{{4qvJZin
server:
  port: 9090
---
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.6.54/kiimate?autoReconnect=true
    username: root
    password: wave
logging:
  level:
    com.sinewang: DEBUG
    one.kii: DEBUG
---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://10.10.10.44:33307/kiimate?autoReconnect=true