spring:
  profiles: common
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 9090
---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost/metamate?autoReconnect=true
    username: root
    password: wave
---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://10.10.10.44:33307/metamate?autoReconnect=true
    username: root
    password: 2fJicd{{4qvJZin
---
spring:
  profiles: home
  datasource:
    url: jdbc:mysql://home.sinewang.com/metamate?autoReconnect=true
    username: root
    password: wave