spring:
  profiles: common
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 9090
logging:
  level:
    com.sinewang.metamate.core.dai.mapper: DEBUG
---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost/metamate?autoReconnect=true
    username: root
    password: wave
---
spring:
  profiles: home
  datasource:
    url: jdbc:mysql://mysql.sinewang.com/metamate?autoReconnect=true
    username: root
    password: wave